### ISSUE TITLE
Memory leak in Python when loadIndex(..., load_data = True) (again again)

### ISSUE THREAD

**Issue by sullivanzheng** [nmslib/nmslib#398] opened 2019-06-19 04:28 UTC
Hi,

I used nmslib to create an index for 100000 vectors with 200 dimensions with HNSW and cosinesimil. This index was saved to disk with option save_data=True.

If you load the index from disk with load_data=True, then it seems to me that loaded data will never be released from memory causing a memory leak.

The following code can reproduce this problem:
`import nmslib
import numpy.random as npr
import numpy as np
import gc

for i in range(100):
  index = nmslib.init('cosinesimil', [], 'hnsw',
                     nmslib.DataType.DENSE_VECTOR,
                     nmslib.DistType.FLOAT)
  query =npr.randn(100, 200).astype(np.float32)
  
  #Load a hnsm index previously created by index.saveIndex(..., save_data=True)
  index.loadIndex('hnsm_index_store', load_data=True) 
  for idx in range(1):
    nn = nmslib.knnQueryBatch(index, 4, 1,query)
    
  #comment it out or not, the memory leak will appear any way
  nmslib.freeIndex(index) 
  
  gc.collect()
gc.collect()`

**Comment by searchivarius** [comment] 2019-06-19 09:15
Thank you for noticing. I have committed a fix: could you install a version from the develop branch and check if the leak disappears? https://github.com/nmslib/nmslib/tree/develop

**Comment by searchivarius** [comment] 2019-06-19 09:55
@sullivanzheng hold on a moment, I am going to double-check the fix.

**Comment by searchivarius** [comment] 2019-06-20 00:51
Hi @sullivanzheng could you try the develop branch now? You need to install it locally from the ``python_bindings`` folder:
```
rm -rf build ; sudo python setup.py install
```
Make sure you deleted the previous version, e.g,:
```
sudo pip uninstall nmslib
```

I think I have fixed it now, but I will also need to set up good unit-like tests to catch leaks in the future. Turns out, it's a bit tricky to test for memory leaks automatically, b/c memory usage is a bit unpredictable, esp., with the garbage collector.

Thanks!

**Closed** 2019-06-23 16:36 UTC

**Comment by searchivarius** [comment] 2019-06-23 17:57
Hi @sullivanzheng the new minor release 1.8.1 should have fixed this error. I have also wrote a regression test to prevent at least some of these bugs in the future. If it still doesn't work for you, please, re-open the issue (with additional comments). Thank you!
