### ISSUE TITLE
HNSW and NSW do not return number of neighbours I need

### ISSUE THREAD

**Issue by adtsvetkov** [nmslib/nmslib#479] opened 2021-05-22 15:39 UTC
Hello,
I'm trying to find large amount of neighbours for my data:

```python
hnsw = nmslib.init(method = 'hnsw', space = 'angulardist')
hnsw.addDataPointBatch(train_features) # train_features 49950 х 322
hnsw.createIndex()

k = 1000

features_len = []
for i in range(test_features.shape[0]): # test_features 50 x 322
    features, distance = hnsw.knnQuery(test_features[i], k=k)
    features_len.append(len(features))
print(features_len)
```

```
Out:
[233, 210, 163, 204, 291, 202, 82, 208, 248, 166, 223, 261, 205, 225, 273, 218, 244, 184, 256, 230, 149, 260, 198, 292, 180, 294, 246, 234, 251, 273, 237, 271, 190, 217, 264, 241, 272, 251, 245, 213, 123, 123, 230, 143, 243, 230, 173, 228, 176, 238]
```
But I need 1000 neighbours!

Same thing happens using `sw-graph`. How can I fix it?

**Comment by searchivarius** [comment] 2021-05-22 17:02
Hi @adtsvetkov I think currently it's not possible to meaningfully enforce that the number of candidates is always k.

**Comment by yurymalkov** [comment] 2021-05-23 03:30
Hm. I thought it is enforced in nmslib. I'd suggest to check if the data has duplicates, which might make algorithms fail.

**Comment by searchivarius** [comment] 2021-05-23 20:04
@yurymalkov good suggestion, thank you. Yes, usually, there's little reason why we will get < K results. However, getting exactly K isn't enforced. It seems to be relatively easy to support this feature. However, I wouldn't do it right now, b/c it might have a performance impact (though with a perfect implementation it shouldn't). Also for this kind of data, bruteforce search could be fast enough.

I am closing this issue, it's a duplicate of #172. I will hopefully fix this someday, but not immediately.

**Closed by searchivarius** 2021-05-23 20:04 UTC
